### ISSUE TITLE
Auto layout after item drag/drop has a different behavior than explicitly calling "layout"

### ISSUE THREAD

**Issue by Omarkth** [metafizzy/packery#269] opened 2015-05-18 10:49 UTC
Check the case here: http://jsfiddle.net/omarkth/px6932qb/3/

Steps:
1) Drag the green box and drop it in the middle of the screen, it will auto-layout and the green box will return to the top of the page (top=0) but the (left) remains the same as where it was dropped
2) Press the "Layout" button, the green box will stack next to the purple box (green left = purple width)

Problem:
Is this normal? how can I achieve the final result of this without having to call the layout explicitly? simply, I need all the boxes to be auto aligned next to each other after the drag/drop.

**Comment by desandro** [comment] 2015-05-18 12:11
Thanks for reporting this issue and providing a test case :)

> Is this normal?

Yes, this is the intended behavior. The Drag & drop logic works a bit different from normal `layout` logic: the dragged item is positioned first and all other items are laid out around it.

Having the drag position be the same as the laid-out position is a legitimate request. Closing this issue here as a duplicate of #4.

**Closed by desandro** 2015-05-18 12:11 UTC
