### ISSUE TITLE
getBoundingClientRect being calculated differently on IE10/11

### ISSUE THREAD

**Issue by harrybui** [metafizzy/packery#209] opened 2014-09-19 18:49 UTC
I have a 3 column layout with same size cards. The first card is a stamped card and cannot be rearranged. I am using Draggabilly to allow drag and drop to rearrange the cards.

I was running into an issue in IE10/11 where cards were not being placed properly because the calculations were slightly off. After some digging I found that in IE10/11, the getBoundingClientRect were returning top/bottom with high precision (ex: 249.70999145507812). In Chrome, this is rounded to 250.

The high precision was causing `canFit( rect )' to return false because it thinks that the dragged card cannot fit the space. For example, this.width=249.70999145507812, rec.width=250.

```
Rect.prototype.canFit = function( rect ) {
  return this.width >= rect.width && this.height >= rect.height;
};

Packer.prototype.pack = function( rect ) {
  for ( var i=0, len = this.spaces.length; i < len; i++ ) {
    var space = this.spaces[i];
    if ( space.canFit( rect ) ) {
      this.placeInSpace( rect, space );
      break;
    }
  }
};
```

My fix was to round the numbers using `Math.round`. I'm not sure if this is the most ideal fix, but here is my solution.

```
Outlayer.prototype._getBoundingRect = function() {
  // get bounding rect for container element
  var boundingRect = this.element.getBoundingClientRect();
  var size = this.size;
  console.log("Top" + boundingRect.top);
  console.log("Bottom" + boundingRect.bottom);
  this._boundingRect = {
    left: boundingRect.left + size.paddingLeft + size.borderLeftWidth,
    top: Math.round( boundingRect.top ) + size.paddingTop + size.borderTopWidth,
    right: boundingRect.right - ( size.paddingRight + size.borderRightWidth ),
    bottom: Math.round( boundingRect.bottom ) - ( size.paddingBottom + size.borderBottomWidth )
  };
};
```

**Comment by desandro** [comment] 2015-01-10 19:55
Closing as a duplicate of #227. Try updating Packery to `v1.3.2`, which has fixes for these pixel-rounding bugs.

**Closed by desandro** 2015-01-10 19:55 UTC
