### ISSUE TITLE
How to pin items on top progressively?

### ISSUE THREAD

**Issue by ableslayer** [metafizzy/packery#467] opened 2017-09-06 08:06 UTC
I'm trying to do a pin top top using packery. 

For example I have 10 items, from 1-10 in that order. 

If I click on **5** to pin it, it will go to top so the order will now be 
5-2-3-4-6-7-8-9-10. 

If I click on **9**, the order will be 
5-9-2-3-4-6-7-8-10
and so on.

I have a codepen here but whenever I click an item, the item that was already pinned gets to the last spot. So when I click on **9**, it will be
9-2-3-4-6-7-8-10-5

**Test case:** https://codepen.io/ableslayer/pen/rzbXPg

**Comment by desandro** [comment] 2017-09-06 12:41
Thanks for reporting this issue. Looks the trouble is caused by Packery v2's layout algorithm, which aims to maintain it's horizontal position. This could be resolved by using Packery v1 layout algorithm. We already have an issue open for adding back that feature. See #353

**Closed by desandro** 2017-09-06 12:41 UTC
