### ISSUE TITLE
Offer hosted SSL version

### ISSUE THREAD

**Issue by charlieholder** [metafizzy/packery#142] opened 2014-02-19 20:59 UTC
I'm running into an issue where the http hosted version cannot be served up on my https connection. Specifically Chrome is blocking the script because it thinks it's unsafe. I can manually allow it locally, but that's not possible to do for every site visitor. I can definitely download and host locally, but would love to see a hosted option.

**Comment by desandro** [comment] 2015-01-10 20:05
Closing as a duplicate of #16

**Closed by desandro** 2015-01-10 20:05 UTC
